version: "3"

services:
  node-app:
    build: .
    container_name: "express-app-container"
    depends_on: ['mongo']

    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  mongo:
    image: mongo
    restart: always
    container_name: "mongo_db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on: ['mongo']
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo_db:27017/

volumes:
  mongo-db: