version: "3"

services:
  node-app:
    build: .
    container_name: "express-app-container"
    depends_on: ['postgres']
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

#  mongo:
#    image: mongo
#    restart: always
#    container_name: "mongo_db"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    volumes:
#      - mongo-db:/data/db
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    depends_on: ['mongo']
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
#      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo_db:27017/

  redis:
    image: redis
    depends_on: ['postgres']

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on: ['node-app']

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    depends_on: ['postgres']

volumes:
  mongo-db:
  postgres-db: